geoff_bq:
  outputs:
    dev:
      dataset: nba
      fixed_retries: 1
      keyfile: /opt/.dbt/dbt-user-bq-creds.json
      location: US
      method: service-account
      priority: interactive
      project: geoff-kaufman
      threads: 1
      timeout_seconds: 300
      type: bigquery
  target: dev
